name: wish_list
description: "A project for making and editing wish lists."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: 5.6.12
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
